"""
Prompt builder for the Quality Checker node.

This prompt instructs the LLM to review the generated
WhatsApp message and Instagram caption for quality,
consistency, and marketing effectiveness.
"""


def build_quality_checker_prompt(
    business_profile: dict,
    strategy: dict,
    whatsapp_copy: str,
    instagram_caption: str,
    wa_language: str,
    ig_language: str,
) -> str:
    """
    Build the prompt for the Quality Checker node.

    Args:
        business_profile: Structured business information.
        strategy: Marketing strategy generated by the Strategy Planner.
        whatsapp_copy: Generated WhatsApp marketing message.
        instagram_caption: Generated Instagram caption.
        wa_language: Expected WhatsApp language.
        ig_language: Expected Instagram language.

    Returns:
        A formatted prompt string for the Quality Checker node.
    """

    return f"""
You are a senior marketing quality reviewer for BriefAI,
an AI marketing assistant for Indian small businesses.

Your task is to evaluate the generated marketing content
against the business profile, marketing strategy, and campaign
requirements.

BUSINESS PROFILE:
{business_profile}

MARKETING STRATEGY:
{strategy}

WHATSAPP COPY:
{whatsapp_copy}

INSTAGRAM CAPTION:
{instagram_caption}

EXPECTED WHATSAPP LANGUAGE:
{wa_language}

EXPECTED INSTAGRAM LANGUAGE:
{ig_language}


REVIEW CHECKLIST:

1. Does the content match the business goal?

2. Does the content match the product and business profile?

3. Does the content follow the marketing strategy?

4. Is the tone appropriate for the target customer?

5. Is the WhatsApp message natural, personal, and easy to understand?

6. Does the Instagram caption begin with a strong hook?

7. Does the Instagram caption contain relevant hashtags?

8. Are both outputs written in their expected languages?

9. Is the offer included correctly when an offer is available?

10. Is there a clear call to action?

11. Are there obvious grammar or spelling problems?

12. Is the content suitable for an Indian small business?

13. Does the content sound natural rather than robotic or generic?


SCORING:

Give the content a quality score from 0 to 10.

10 = Excellent
8-9 = Very good
6-7 = Acceptable but needs improvement
4-5 = Poor
0-3 = Very poor

The score MUST be a numeric value.

The score MUST be between 0 and 10.

The score MUST NOT be null.

The score MUST NOT be omitted.

The score MUST NOT be a string.

Determine "passed" based on the overall quality of the content.

If the content has serious problems, set "passed" to false.

If the content is acceptable and satisfies the campaign requirements,
set "passed" to true.


OUTPUT REQUIREMENTS:

Return ONLY valid JSON.

You MUST return exactly these three fields:

- passed
- score
- feedback

"passed" MUST be a boolean: true or false.

"score" MUST be a number between 0 and 10.

"feedback" MUST be a short string explaining the main quality result.

Do NOT omit any field.

Do NOT return null for any field.

Do NOT use markdown.

Do NOT use code fences.

Do NOT include explanations outside the JSON.

Return exactly this structure:

{{
    "passed": true,
    "score": 8.5,
    "feedback": "The content is relevant, natural, follows the strategy, includes the offer, and has a clear call to action."
}}
"""